document.write ('<!--\n');
document.write ('Ange filnamnet i Extra HTML fältet\n');
document.write ('Angel Url');
document.write ("'");
document.write ('en i Click URL fältet\n');
document.write (' -->\n');
document.write ('\n');
document.write ('<a href="http://oas.veckorevyn.com/5c/btannonstorg/www.veckorevyn.com/livsstil/15-anledningar-till-varfor-en-katt-ar-battre-an-en-pojkvan/L18/L31/197930677/k2a4/ilike.se/btad_Ulsans/Ulsan_ny_130321.html/4c734d765131462b74314d41414d7a48" target="_blank">\n');
document.write ('<img src="http://oas.veckorevyn.com/0/ilike.se/btad_Ulsans/Ulsan_Ny_130321.jpg"/>\n');
document.write ('</a>');
